// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{path}": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Download file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object path (wildcard)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "file content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "private file without valid token",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "403": {
                        "description": "path is a directory or symlink escape",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Upload file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object path (wildcard)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer \u003cAPI_KEY\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "public or private",
                        "name": "X-Access",
                        "in": "header"
                    },
                    {
                        "description": "raw file bytes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\\\"path\\\":\\\"/\u003cpath\u003e\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "file"
                ],
                "summary": "Delete file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object path (wildcard)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer \u003cAPI_KEY\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    }
                }
            }
        },
        "/{path}/acl": {
            "get": {
                "description": "Access via /\u003cpath\u003e?acl (bare query parameter). Documented here as /{path}/acl for OpenAPI 2.0 tooling compatibility; use the ?acl form in actual requests.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "acl"
                ],
                "summary": "Get ACL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object path (wildcard)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "must be the bare key 'acl'",
                        "name": "acl",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer \u003cAPI_KEY\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Access via /\u003cpath\u003e?acl (bare query parameter). Documented here as /{path}/acl for OpenAPI 2.0 tooling compatibility; use the ?acl form in actual requests.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "acl"
                ],
                "summary": "Set ACL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object path (wildcard)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "must be the bare key 'acl'",
                        "name": "acl",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer \u003cAPI_KEY\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "access payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.aclBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Access via /\u003cpath\u003e?acl (bare query parameter). Documented here as /{path}/acl for OpenAPI 2.0 tooling compatibility; use the ?acl form in actual requests.",
                "tags": [
                    "acl"
                ],
                "summary": "Delete ACL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object path (wildcard)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "must be the bare key 'acl'",
                        "name": "acl",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer \u003cAPI_KEY\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apierror.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apierror.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "server.aclBody": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "filehub API",
	Description:      "Self-hosted file server with per-path ACL.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
